	alter table COMMENT 
        drop constraint FK63717A3FA7CD013E

    alter table COMMENT 
        drop constraint FK63717A3FAC90337E

    alter table POTENTIAL_PARTICIPANTS 
        drop constraint FK8118E64147140EFE

    alter table POTENTIAL_PARTICIPANTS 
        drop constraint FK8118E641AC90337E

    alter table WORKSHOP 
        drop constraint FK30C7A187B1F406B7

    alter table WORKSHOP 
        drop constraint FK30C7A187A7CD013E

    alter table WORKSHOP 
        drop constraint FK30C7A1873F837396

    alter table WORKSHOP_SESSION 
        drop constraint FKE158DFBEAE35BE4A

    alter table WORKSHOP_SPEAKERS 
        drop constraint FK76C6E80C47140EFE

    alter table WORKSHOP_SPEAKERS 
        drop constraint FK76C6E80CAC90337E

    drop table COMMENT if exists

    drop table POTENTIAL_PARTICIPANTS if exists

    drop table RESSOURCE if exists

    drop table USER if exists

    drop table WORKSHOP if exists

    drop table WORKSHOP_SESSION if exists

    drop table WORKSHOP_SPEAKERS if exists

    create table COMMENT (
        id bigint generated by default as identity,
        comment varchar(255),
        creation_date timestamp,
        author_id bigint,
        workshop_id bigint,
        primary key (id)
    )

    create table POTENTIAL_PARTICIPANTS (
        workshop_id bigint not null,
        user_id bigint not null,
        primary key (workshop_id, user_id)
    )

    create table RESSOURCE (
        id bigint generated by default as identity,
        ws_support_file varchar(255),
        ws_support_link varchar(255),
        primary key (id)
    )

    create table USER (
        id bigint generated by default as identity,
        charterAgree boolean,
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        picture varchar(255),
        role varchar(255),
        primary key (id)
    )

    create table WORKSHOP (
        id bigint generated by default as identity,
        description varchar(1000),
        image varchar(255),
        subject varchar(255),
        summary varchar(300),
        author_id bigint,
        workshopRessources_id bigint,
        workshopSession_id bigint,
        primary key (id)
    )

    create table WORKSHOP_SESSION (
        id bigint generated by default as identity,
        doodle_url varchar(255),
        location varchar(255),
        nextPlay timestamp,
        speaker_id bigint,
        primary key (id)
    )

    create table WORKSHOP_SPEAKERS (
        workshop_id bigint not null,
        user_id bigint not null,
        primary key (workshop_id, user_id)
    )

    alter table COMMENT 
        add constraint FK63717A3FA7CD013E 
        foreign key (author_id) 
        references USER

    alter table COMMENT 
        add constraint FK63717A3FAC90337E 
        foreign key (workshop_id) 
        references WORKSHOP

    alter table POTENTIAL_PARTICIPANTS 
        add constraint FK8118E64147140EFE 
        foreign key (user_id) 
        references USER

    alter table POTENTIAL_PARTICIPANTS 
        add constraint FK8118E641AC90337E 
        foreign key (workshop_id) 
        references WORKSHOP

    alter table WORKSHOP 
        add constraint FK30C7A187B1F406B7 
        foreign key (workshopRessources_id) 
        references RESSOURCE

    alter table WORKSHOP 
        add constraint FK30C7A187A7CD013E 
        foreign key (author_id) 
        references USER

    alter table WORKSHOP 
        add constraint FK30C7A1873F837396 
        foreign key (workshopSession_id) 
        references WORKSHOP_SESSION

    alter table WORKSHOP_SESSION 
        add constraint FKE158DFBEAE35BE4A 
        foreign key (speaker_id) 
        references USER

    alter table WORKSHOP_SPEAKERS 
        add constraint FK76C6E80C47140EFE 
        foreign key (user_id) 
        references USER

    alter table WORKSHOP_SPEAKERS 
        add constraint FK76C6E80CAC90337E 
        foreign key (workshop_id) 
        references WORKSHOP
